export const LEGACY_RECIPE_FILTER_OPTIONS = {
  cuisines: [
    "African",
    "American",
    "Asian",
    "Cajun",
    "Chinese",
    "Creole",
    "Caribbean",
    "Central/South American",
    "French",
    "German",
    "Greek",
    "Indian",
    "Italian",
    "Mediterranean",
    "Mexican",
    "Middle Eastern",
    "Russian",
    "Southwestern",
    "Spanish",
    "Thai",
  ],
  diets: [
    "Dairy Free",
    "Fat Free",
    "Gluten-Free",
    "High Fiber",
    "Low Fat",
    "Low sodium",
    "Low Sugar",
    "Vegan",
    "Vegetarian",
    "Nutrient Rich",
    "Paleo",
  ],
  holidays: [
    "New Year's Eve/Day",
    "Valentine's Day",
    "St. Patrick's Day",
    "Easter",
    "Mother's Day",
    "Memorial Day",
    "Father's Day",
    "4th of July",
    "Labor Day",
    "Halloween",
    "Thanksgiving",
    "Hanukkah",
    "Christmas",
    "Anniversary",
    "Birthday",
    "Cinco de Mayo",
    "Graduation",
  ],
  cookingMethods: [
    "Bake",
    "Broil",
    "Grill",
    "Roast",
    "Slow Cooker",
    "Stovetop",
  ],
  categories: [
    "Family Favorites",
    "Seasonal",
    "Quick Meals",
    "Entertaining",
  ],
  courses: [
    "Dinner",
    "Breakfast",
    "Lunch",
    "Appetizer",
    "Snack",
    "Beverage",
    "Salad",
    "Side",
    "Soup",
  ],
  mainIngredients: [
    "Beans",
    "Beef",
    "Cheese",
    "Chocolate",
    "Dairy",
    "Eggs",
    "Fruit",
    "Grains",
    "Lamb",
    "Legumes",
    "Nuts",
    "Pasta",
    "Pork",
    "Poultry",
    "Rice",
    "Seafood",
    "Tofu/Soy",
    "Vegetables",
  ],
} as const;
